name: ColorMe
main: com.sparkedia.valrix.ColorMe.ColorMe
version: 1.6
author: Valrix
description: Sets custom prefix to individual players
commands:
    colorme:
        description: Give player name a color
        usage: |
               <> = Required [] = Optional
               /<command> list - Shows list of colors
               /<command> <name> - Remove color
               /<command> <color> [name] - Set color