name: ColorMe
main: de.xghostkillerx.colorme.ColorMe
version: 3.4 dev 1
author: xGhOsTkiLLeRx
authors: [Valrix]
website: http://bit.ly/bukkitdevcolorme
website: http://bit.ly/colormebukkit
description: Sets custom color, prefixes and suffixes to player's name
commands:
    color:
        usage: /color help - to see the help
        aliases: [colorme, colour]
        description: Gives the player name a color
    prefix:
        usage: /prefix help - to see the help
        description: Gives the player name a prefix
    suffix:
        usage: /suffix help - to see the help
        description: Gives the player name a suffix
permissions:
    colorme.list:
        default: true
        description: Allows player to see list of color codes
    colorme.self:
        default: op
        description: Allows setting of own color
    colorme.other:
        default: op
        description: Allows setting of other player's color
    colorme.remove:
        default: op
        description: Removes color
    colorme.get:
        default: op
        description: Gets actual color
    colorme.*:
        children:
            colorme.list: true
            colorme.self: true
            colorme.other: true
            colorme.remove: true
            colorme.get: true
        description: Allows all commands
softdepend: [Vault, Spout]