name: ColorMe
main: de.dustplanet.colorme.ColorMe
version: 3.5 dev7
author: xGhOsTkiLLeRx
authors: [Valrix]
website: http://bit.ly/bukkitdevcolorme
website: http://bit.ly/colormebukkit
description: Sets custom color, prefixes and suffixes to player's name
commands:
    color:
        usage: /color help - to see the help
        aliases: [colorme, colour]
        description: Gives the player name a color
    prefix:
        usage: /prefix help - to see the help
        aliases: [prefixme, prefixer]
        description: Gives the player name a prefix
    suffix:
        usage: /suffix help - to see the help
        aliases: [suffixme, suffixer]
        description: Gives the player name a suffix
    group:
        usage: /group help - to see the help
        aliases: [groups]
        description: Commands for the group system
permissions:
    colorme.list:
        default: true
        description: Allows player to see list of color codes
    colorme.self.*:
        children:
            colorme.self.black: true
            colorme.self.dark_blue: true
            colorme.self.dark_green: true
            colorme.self.dark_aqua: true
            colorme.self.dark_red: true
            colorme.self.dark_purple: true
            colorme.self.gold: true
            colorme.self.gray: true
            colorme.self.dark_gray: true
            colorme.self.blue: true
            colorme.self.green: true
            colorme.self.aqua: true
            colorme.self.red: true
            colorme.self.light_purple: true
            colorme.self.yellow: true
            colorme.self.magic: true
            colorme.self.white: true
            colorme.self.random: true
            colorme.self.rainbow: true
            colorme.self.bold: true
            colorme.self.italic: true
            colorme.self.underline: true
            colorme.self.strikethrough: true
            colorme.self.custom: true
    colorme.self.black:
        default: op
        description: Allows setting of own color
    colorme.self.dark_blue:
        default: op
        description: Allows setting of own color
    colorme.self.dark_green:
        default: op
        description: Allows setting of own color
    colorme.self.dark_aqua:
        default: op
        description: Allows setting of own color
    colorme.self.dark_red:
        default: op
        description: Allows setting of own color
    colorme.self.dark_purple:
        default: op
        description: Allows setting of own color
    colorme.self.gold:
        default: op
        description: Allows setting of own color
    colorme.self.gray:
        default: op
        description: Allows setting of own color
    colorme.self.dark_gray:
        default: op
        description: Allows setting of own color
    colorme.self.blue:
        default: op
        description: Allows setting of own color
    colorme.self.green:
        default: op
        description: Allows setting of own color
    colorme.self.aqua:
        default: op
        description: Allows setting of own color
    colorme.self.red:
        default: op
        description: Allows setting of own color
    colorme.self.light_purple:
        default: op
        description: Allows setting of own color
    colorme.self.yellow:
        default: op
        description: Allows setting of own color
    colorme.self.magic:
        default: op
        description: Allows setting of own color
    colorme.self.white:
        default: op
        description: Allows setting of own color
    colorme.self.random:
        default: op
        description: Allows setting of own color
    colorme.self.rainbow:
        default: op
        description: Allows setting of own color
    colorme.self.custom:
        default: op
        description: Allows setting of own color
    colorme.self.bold:
        default: op
        description: Allows setting of own color
    colorme.self.italic:
        default: op
        description: Allows setting of own color
    colorme.self.underline:
        default: op
        description: Allows setting of own color
    colorme.self.strikethrough:
        default: op
        description: Allows setting of own color
    colorme.other:
        default: op
        description: Allows setting of other player's color
    colorme.remove:
        default: op
        description: Removes color
    colorme.get:
        default: op
        description: Gets actual color
    colorme.global:
        default: op
        description: Sets the global color
    colorme.free:
        default: op
        description: No costs for coloring
    colorme.chat:
        default: op
        description: Permission for coloring signs
    colorme.sign:
        default: op
        description: Permission to color the chat
    colorme.*:
        children:
            colorme.list: true
            colorme.self.*: true
            colorme.other: true
            colorme.remove: true
            colorme.get: true
            colorme.global: true
            colorme.free: true
            colorme.chat: true
            colorme.sign: true
        description: Allows all commands for ColorMe
    prefixer.list:
        default: true
        description: Allows player to see list of color codes
    prefixer.self:
        default: op
        description: Allows setting of own prefix
    prefixer.other:
        default: op
        description: Allows setting of other player's prefix
    prefixer.remove:
        default: op
        description: Removes prefix
    prefixer.get:
        default: op
        description: Gets actual prefix
    prefixer.global:
        default: op
        description: Sets the global prefix
    prefixer.free:
        default: op
        description: No costs for prefixing
    prefixer.nofilter:
        default: op
        description: No filter for prefixing
    prefixer.*:
        children:
            prefixer.list: true
            prefixer.self: true
            prefixer.other: true
            prefixer.remove: true
            prefixer.get: true
            prefixer.global: true
            prefixer.free: true
            prefixer.nofilter: true
        description: Allows all commands for Prefixer
    suffixer.list:
        default: true
        description: Allows player to see list of color codes
    suffixer.self:
        default: op
        description: Allows setting of own suffix
    suffixer.other:
        default: op
        description: Allows setting of other player's suffix
    suffixer.remove:
        default: op
        description: Removes suffix
    suffixer.get:
        default: op
        description: Gets actual suffix
    suffixer.global:
        default: op
        description: Sets the global suffix
    suffixer.free:
        default: op
        description: No costs for suffixing
    suffixer.nofilter:
        default: op
        description: No filter for suffixing
    suffixer.*:
        children:
            suffixer.list: true
            suffixer.self: true
            suffixer.other: true
            suffixer.remove: true
            suffixer.get: true
            suffixer.global: true
            suffixer.free: true
            suffixer.nofilter: true
        description: Allows all commands for Suffixer
softdepend: [Vault, Spout]