name: ColorMe
main: de.xghostkillerx.colorme.ColorMe
version: 3.0
author: xGhosTkiLLeRx
authors: [Valrix]
description: Sets custom color to player's name
commands:
    color:
        usage: /color help - to see the help
        aliases: [colorme]
        description: Gives the player name a color
permissions:
    colorme.list:
        default: true
        description: Allows player to see list of color codes
    colorme.self:
        default: op
        description: Allows setting of own color
    colorme.other:
        default: op
        description: Allows setting of other player's color
    colorme.remove:
        default: op
        description: Allows removal of other player's color
    colorme.*:
        children:
            colorme.list: true
            colorme.self: true
            colorme.other: true
            colorme.remove: true
        description: Allows all commands
softdepend: [Vault]