name: ColorMe
main: com.sparkedia.valrix.ColorMe.ColorMe
version: 1.1
author: Valrix
description: Sets custom prefix to individual players
commands:
    color:
        description: Give player name a color
        usage: /<command>